// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase App.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqd8GRT4jNf3jaiokk_lKWa-9IYKXkMM',
    appId: '1:919980264785:web:c273054d43e7d9574cd770',
    messagingSenderId: '919980264785',
    projectId: 'liftlab-9de39',
    authDomain: 'liftlab-9de39.firebaseapp.com',
    storageBucket: 'liftlab-9de39.appspot.com',
    measurementId: 'G-3Z6165QK99',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapGwHfR3hzx3WWAcAAy9qOQe3Nl0AAxs',
    appId: '1:919980264785:ios:785ce7ac2857d6ad4cd770',
    messagingSenderId: '919980264785',
    projectId: 'liftlab-9de39',
    storageBucket: 'liftlab-9de39.firebasestorage.app',
    iosBundleId: 'com.shivasajay.liftlab',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tVnBv5wKfALtUTeTEag2sq79a8l4cS8',
    appId: '1:919980264785:android:0d1f33a1d8e6011d4cd770',
    messagingSenderId: '919980264785',
    projectId: 'liftlab-9de39',
    storageBucket: 'liftlab-9de39.firebasestorage.app',
  );
}
